btrfssnap: rewrite in perl, mostly copied from zfssnapman

diff --git a/btrfssnap b/btrfssnap
--- a/btrfssnap
+++ b/btrfssnap
@@ -1,20 +1,87 @@
-#! /bin/bash
+#! /usr/bin/perl
 
-for dir in music pics ; do
-    /sbin/btrfs subvolume snapshot /mnt/btrfs/$dir /mnt/btrfs/snaps/$dir-`date +%Y%m%d-%H%M%S`
-done
+use strict;
+use warnings;
 
-if [[ ! -d /mnt/btrfs2/.snaps ]]; then
-	mkdir /mnt/btrfs2/.snaps
-fi
-for dir in home; do
-	/sbin/btrfs subvolume snapshot /mnt/btrfs2/$dir /mnt/btrfs2/.snaps/$dir-`date +%Y%m%d-%H%M%S`
-done
+use Getopt::Long;
+use POSIX qw( strftime mktime );
+use Data::Dumper;
 
-if [[ ! -d /mnt/btrfs2/home/.snaps ]]; then
-        mkdir /mnt/btrfs2/home/.snaps
-fi
-for dir in spin; do
-	/sbin/btrfs subvolume snapshot /mnt/btrfs2/home/$dir /mnt/btrfs2/home/.snaps/$dir-`date +%Y%m%d-%H%M%S`
-done
+# inifinite snapshots for some filesystems
+
+our %months=(Jan => 0,
+             Feb => 1,
+             Mar => 2,
+             Apr => 3,
+             May => 4,
+             Jun => 5,
+             Jul => 6,
+             Aug => 7,
+             Sep => 8,
+             Oct => 9,
+             Nov => 10,
+             Dec => 11,
+            );
+
+our $BTRFSROOT='/data';
+our $DESTROY=1;
+our $SNAP=1;
+
+our %btrfs=( 'backups'         => 365,
+             'pics'            => 365,
+             'music'           => 365,
+             'home'            => 365,
+             'home/spin'       => 365,
+             'video'           => 7,
+             'home/spin/down'  => 7,
+         );
+
+GetOptions(
+           'btrfs=s'  => \$BTRFSROOT,
+           'snap!'    => \$SNAP,
+           'destroy!' => \$DESTROY,
+          );
+
+my $time=strftime('%F%T',localtime(time()));
+$time =~ s/[\:\-]//g;
+
+
+my @subvols=map { my @a=split(/\s+/,$_); $a[6]; } (`btrfs sub list $BTRFSROOT`);
+chomp @subvols;
+
+while(my ($btrfs,$days)=each(%btrfs)) {
+  if($DESTROY) {
+    foreach my $subvol (sort(@subvols)) {
+      unless($subvol =~ /^snapshots\/\E$btrfs\/(\d+)$/) {
+        next;
+      }
+      my $snap=$1;
+      unless($snap =~ /(\d\d\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)/) {
+        warn "unable to parse the snap date: $snap";
+        next;
+      }
+      my $age=mktime($6,$5,$4,$3,($2-1),($1-1900));
+      if(time() > ($age + ($days * 24 * 60 * 60 ))) {
+        #printf("removing: %s created at %s\n",$snap,strftime('%F %T',localtime($age)));
+        my @com=qw( btrfs subvolume delete );
+        push(@com,join('/',$BTRFSROOT,$subvol));
+        print join(" ",@com)."\n";
+        system(@com);
+        if($? != 0) {
+          warn "unable to delete subvolume";
+        }
+      }
+    }
+  }
+  if($SNAP) {
+    my @com=qw( btrfs subvolume snapshot );
+    push(@com,join('/',$BTRFSROOT,$btrfs));
+    push(@com,join('/',$BTRFSROOT,'snapshots',$btrfs,$time));
+    print join(' ',@com)."\n";
+    system(@com);
+    if($? != 0) {
+      warn "unable to create snapshot";
+    }
+  }
+}
 
